"""Test for overwrite functionality fix.

This test ensures that _overwrite fields are processed after field renaming
so they can properly override renamed fields from original NetCDF files.
"""

import amocatlas.read as read


def test_dso_acknowledgment_overwrite_applied():
    """Test that DSO acknowledgment_overwrite properly overrides original file acknowledgement field.

    This test verifies the fix for the issue where:
    1. Original file has 'acknowledgement' field
    2. YAML has 'acknowledgment_overwrite' field
    3. Field renaming converts 'acknowledgement' → 'acknowledgment'
    4. Overwrite processing should happen AFTER renaming to properly override
    """
    # Load DSO dataset which has acknowledgment_overwrite in YAML
    ds = read.dso()

    # Get the final acknowledgment field
    ack = ds.attrs.get("acknowledgment", "NOT_FOUND")

    # Verify the YAML overwrite text appears (not the original file text)
    expected_yaml_start = "The DSO was generated by the University of Hamburg"
    original_file_start = "The timeseries was generated by Institution"

    # Should contain YAML text, not original file text
    assert (
        expected_yaml_start in ack
    ), f"acknowledgment_overwrite not applied. Got: {ack[:100]}..."
    assert (
        original_file_start not in ack
    ), f"Original file acknowledgment not overridden. Got: {ack[:100]}..."

    # Verify no _overwrite fields remain in final dataset
    overwrite_fields = [k for k in ds.attrs.keys() if k.endswith("_overwrite")]
    assert (
        overwrite_fields == []
    ), f"_overwrite fields not cleaned up: {overwrite_fields}"


def test_overwrite_after_field_renaming():
    """Test that overwrite processing happens after field renaming.

    This is a more general test that could apply to other datasets with similar issues.
    """
    # Load a dataset that might have field renaming + overwrite conflicts
    ds = read.dso()

    # Check that acknowledgment field exists and contains expected content
    assert "acknowledgment" in ds.attrs, "acknowledgment field missing"

    # The acknowledgment should be from YAML (overwrite), not original file
    ack = ds.attrs["acknowledgment"]

    # YAML acknowledgment mentions specific funding details
    assert "NACLIM" in ack, "YAML acknowledgment content not present"
    assert "University of Hamburg" in ack, "YAML acknowledgment content not present"

    # Original file acknowledgment mentioned different institution name format
    assert (
        "Institution of Oceanography Hamburg" not in ack
    ), "Original file acknowledgment not overridden"


if __name__ == "__main__":
    test_dso_acknowledgment_overwrite_applied()
    test_overwrite_after_field_renaming()
    print("✅ All overwrite fix tests passed!")
