"""Generate ``docs/source/reference/vocabulary.rst`` from ``amocvocab.yml``.

The vocabulary file is the source of truth; the docs table is generated so it cannot
drift. Run after editing ``amocvocab.yml``::

    python -m amocatlas.vocabulary.build_rst

This reads only the vocabulary and writes only the RST; it does not touch the metadata
YAMLs or fabricate anything.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List

HERE = Path(__file__).resolve().parent
DEFAULT_VOCAB = HERE / "amocvocab.yml"
DEFAULT_RST = HERE.parent.parent / "docs" / "source" / "reference" / "vocabulary.rst"


def _load(vocab_path: Path) -> dict:
    import yaml

    with open(vocab_path, "r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _rst_table(headers: List[str], rows: List[List[str]]) -> List[str]:
    """Build a simple reStructuredText grid-free 'list-table' block."""
    out = [".. list-table::", "   :header-rows: 1", "   :widths: auto", ""]
    out.append("   * - " + ("\n     - ".join(headers)))
    for row in rows:
        cells = [c if c else "—" for c in row]
        out.append("   * - " + ("\n     - ".join(cells)))
    out.append("")
    return out


def _cf_cell(entry: dict) -> str:
    status = entry.get("cf_status")
    sn = entry.get("standard_name")
    if status == "exact" and sn:
        return f"``{sn}``"
    related = entry.get("cf_related")
    label = {"units_incompatible": "units-incompatible", "none": "none"}.get(
        status, status or "?"
    )
    if related:
        return f"{label} (nearest ``{related}``)"
    return label


def render(vocab: dict) -> str:
    """Render the vocabulary document as an RST string."""
    version = vocab.get("version", "?")
    table_ver = vocab.get("cf_standard_name_table", "?")
    quantities: Dict[str, dict] = vocab.get("quantities") or {}
    qualifiers: Dict[str, dict] = vocab.get("qualifiers") or {}
    decompositions: Dict[str, dict] = vocab.get("decompositions") or {}

    lines: List[str] = []
    lines.append(".. This file is generated by amocatlas.vocabulary.build_rst.")
    lines.append(".. Do not edit by hand; edit amocvocab.yml and regenerate.")
    lines.append("")
    lines.append("amocvocab — variable vocabulary")
    lines.append("===============================")
    lines.append("")
    lines.append(
        f"Version **{version}**, checked against CF standard-name table "
        f"**{table_ver}**. This table is generated from "
        "``amocatlas/vocabulary/amocvocab.yml``."
    )
    lines.append("")
    lines.append(
        "Each quantity carries a CF ``standard_name`` only when an exact CF name exists "
        "whose canonical units are convertible to the reported units; otherwise the "
        "standard name is null and the nearest CF concept, if any, is noted. See the "
        ":doc:`format` conformance statement for how these are written into files."
    )
    lines.append("")

    # Quantities table
    lines.append("Quantities")
    lines.append("----------")
    lines.append("")
    rows = []
    for key, e in quantities.items():
        rows.append(
            [
                f"``{key}``",
                e.get("long_name", ""),
                e.get("kind", ""),
                _cf_cell(e),
                f"``{e.get('units', '')}``",
                e.get("status", ""),
            ]
        )
    lines += _rst_table(
        ["Name", "Long name", "Kind", "CF standard_name", "Units", "Status"], rows
    )

    # Qualifiers
    if qualifiers:
        lines.append("Qualifiers")
        lines.append("----------")
        lines.append("")
        qrows = [
            [
                f"``{code}``",
                q.get("class", ""),
                str(q.get("order", "")),
                " ".join((q.get("definition") or "").split()),
            ]
            for code, q in qualifiers.items()
        ]
        lines += _rst_table(["Code", "Class", "Order", "Definition"], qrows)

    # Decompositions
    if decompositions:
        lines.append("Decompositions")
        lines.append("--------------")
        lines.append("")
        lines.append(
            "All decompositions are **provisional** in this release: the component "
            "partition is verified where a closure check is recorded, but the scheme "
            "reference is not yet pinned."
        )
        lines.append("")
        drows = []
        for name, d in decompositions.items():
            comps = ", ".join(f"``{c}``" for c in d.get("components", []))
            drows.append(
                [
                    f"``{name}``",
                    f"``{d.get('of', '')}``",
                    comps,
                    d.get("closure", ""),
                    d.get("status", ""),
                ]
            )
        lines += _rst_table(
            ["Decomposition", "Of", "Components", "Closure", "Status"], drows
        )

    return "\n".join(lines) + "\n"


def main(vocab_path: Path = DEFAULT_VOCAB, rst_path: Path = DEFAULT_RST) -> int:
    """Generate the RST file. Returns process exit status."""
    vocab = _load(vocab_path)
    text = render(vocab)
    rst_path.write_text(text, encoding="utf-8")
    print(f"wrote {rst_path} ({len(vocab.get('quantities') or {})} quantities)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
