name: Test documentation build

on:
  pull_request:
    paths:
      - '**.py'
      - '**.ipynb'
      - '**.rst'
      - '**.md'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          cache-environment: true

      - name: Install package (editable)
        shell: bash -l {0}
        run: |
          micromamba run -n amocatlas python -m pip install --upgrade pip
          micromamba run -n amocatlas python -m pip install -e . --no-deps --force-reinstall

      - name: Build documentation
        shell: bash -l {0}
        run: |
          set -e
          micromamba run -n amocatlas jupyter nbconvert --to notebook --execute notebooks/demo.ipynb --output=demo-output.ipynb --ExecutePreprocessor.allow_errors=False
          micromamba run -n amocatlas jupyter nbconvert --to notebook --execute notebooks/demo-convert.ipynb --output=demo-convert-output.ipynb --ExecutePreprocessor.allow_errors=False
          # Copy the paperfigs notebook without executing (requires PyGMT/GMT which aren't available in CI)
          cp notebooks/amoc_paperfigs.ipynb docs/source/amoc_paperfigs-output.ipynb
          mv notebooks/*output.ipynb docs/source/
          pushd docs
          micromamba run -n amocatlas make clean html
          popd
